tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "fish"
brew "git", link: false
brew "git-flow"
brew "go"
brew "nodebrew"
brew "ranger"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
cask "font-hack-nerd-font"
cask "font-ricty-diminished"
cask "visual-studio-code"
